services:
  prometheus-test:
    image: prom/prometheus
    container_name: prometheus-test
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus/:ro
      - ./prometheus_data:/prometheus:rw
    networks:
      - monitor-net

  # Add the ready-made Prometheus example app
  example-app:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
      - "443:443"
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    environment:
      - ALERT_SMTP_FROM=${ALERT_SMTP_FROM}
      - ALERT_SMTP_USER=${ALERT_SMTP_USER}
      - ALERT_SMTP_PASS=${ALERT_SMTP_PASS}
      - ALERT_EMAIL_TO=${ALERT_EMAIL_TO}
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
